Feature/base component button
boostgrade/wtgt_alpha pull request #10
Opened 2021-12-05 13:02 UTC by Akrid782

# [Ссылка на задачу](https://github.com/boostgrade/wtgt_alpha/issues/3)
Задача #3 

# Что было сделано

1. Добавлен localization фразы для кнопки en и ru - для смени языка в приложения
2. Создал ButtonWidget от наследованного от StatelessWidget с кнопкой ElevatedButton - кнопку выбрал такую потому что она с заливкой
3. Задан стиль кнопки в соответствии верстки в figme
4. Было добавлено 3 состояния которые управляются через конструктор
5. Добавил цветовую схему в файл wtgt_alpha\lib\src\ui\res\colors\colors.dart

# Как проверить работу?

1. Выбрать место где будет размещаться кнопка
2. Сделать импорт пакета 'package:where_to_go_today/src/ui/uikit/button_widget.dart'
3. Вставить код в нужное место

```dart 
ButtonWidget(
    title: 'Заголовок кнопки',
    callBackPressed: () {
        print('Hi');
    }, //'передать callback функцию void',
    process: false, // сюда передать true если нужно показать прелоадер, по умолчанию false, не обязательный параметр
    disable: false // сюда передать true если нужно заблокировать кнопку, по умолчанию false, не обязательный параметр
)
```

# Чек-лист

- [X] Функциональность протестирована и работает корректно
- [X] Если в задаче есть верстка - прикреплен скриншот или запись экрана

2021-12-06 06:35 UTC, artem-zaitsev requested changes
небольшие правки

2021-12-06 06:35 UTC, artem-zaitsev commented on lib/src/ui/uikit/button_widget.dart
> +  final void Function()? onSomething;
лучше onTap/onPressed - больше подходит по смыслу(я тогда написал Something для примера)

2021-12-06 06:35 UTC, artem-zaitsev commented on lib/src/ui/uikit/button_widget.dart
> +  final bool process;
bool стоит либо начинать с вопроса: is/was/has..
Но в данном случае можно написать inProcess

2021-12-06 06:35 UTC, artem-zaitsev commented on lib/src/ui/uikit/button_widget.dart
> +          : Container(
тут просто можно было использовать виджет Padding

2021-12-06 06:35 UTC, artem-zaitsev commented on lib/src/ui/uikit/button_widget.dart
> +                valueColor: AlwaysStoppedAnimation<Color>(
Почему Stopped?

2021-12-08 05:57 UTC, Akrid782 commented on lib/src/ui/uikit/button_widget.dart
> +  final void Function()? onSomething;
поправил

2021-12-08 05:59 UTC, Akrid782 commented on lib/src/ui/uikit/button_widget.dart
> +  final bool process;
поправил

2021-12-08 05:59 UTC, Akrid782 commented on lib/src/ui/uikit/button_widget.dart
> +          : Container(
поправил

2021-12-08 06:21 UTC, Akrid782 commented on lib/src/ui/uikit/button_widget.dart
> +                valueColor: AlwaysStoppedAnimation<Color>(
поправил на color

2021-12-08 11:05 UTC, artem-zaitsev approved these changes

2021-12-08 11:05 UTC, merged