Добавил основные стили текста
boostgrade/wtgt_alpha pull request #11
Opened 2021-12-06 07:02 UTC by Akrid782

[# Ссылка на задачу](https://github.com/boostgrade/wtgt_alpha/issues/2)
Задача #2 

# Что было сделано

Дописан абстрактный класс AppTypography стилями текста из фигмы

# Как проверить работу?

В стили текста добавить AppTypography.headLine. 

Импорт
```dart
import 'package:where_to_go_today/src/ui/res/typography/typography.dart';
```
Используем
```dart
Text('Привет', style:AppTypography.headLine);
```
Пример
![image](https://user-images.githubusercontent.com/20724267/144801643-2b05ea23-ba38-4908-9178-809ed0931e48.png)

# Чек-лист

- [X] Функциональность протестирована и работает корректно
- [X] Если в задаче есть верстка - прикреплен скриншот или запись экрана

2021-12-08 11:01 UTC, artem-zaitsev requested changes

2021-12-08 11:01 UTC, artem-zaitsev commented on pubspec.yaml
> +        - asset: assets/fonts/Montserrat-Medium.ttf
а для этих начертаний значение веса почему не указал?

2021-12-08 11:01 UTC, artem-zaitsev commented on pubspec.yaml
> +        - asset: assets/fonts/Montserrat-Medium.ttf
В приложении и 500 и 400 используются

2021-12-12 18:07 UTC, Akrid782 commented on pubspec.yaml
> +        - asset: assets/fonts/Montserrat-Medium.ttf
поправил

2021-12-13 08:07 UTC, artem-zaitsev approved these changes

2021-12-13 08:08 UTC, merged