Запросы для авторизации 1 попытка
boostgrade/wtgt_alpha pull request #26
Opened 2021-12-12 22:51 UTC by Salnikova-EO

# Ссылка на задачу
Задача #16

# Что было сделано
Структура файлов и папок для задачи.
Попытка реализовать retrofit.
Попытка написать модель для одного вида авторизации и для токена

# Как проверить работу?

Пока рано

# Чек-лист

- [ ] Функциональность протестирована и работает корректно
- [ ] Если в задаче есть верстка - прикреплен скриншот или запись экрана

2021-12-13 08:12 UTC, artem-zaitsev reviewed
Направление верное!

2021-12-13 08:12 UTC, artem-zaitsev commented on lib/src/auth/api/models/apple_login_response.dart
> +class AppleLoginResponse {
В целом верно, но не хватает аннотаций из json_serializzable.

Сам класс надо пометить как @JsonSerializable()
и написать factory конструктор и метод toJson
https://pub.dev/packages/json_serializable#example

2021-12-13 08:12 UTC, artem-zaitsev commented on lib/src/auth/services/api/auth_api.dart
> +@RestApi(baseUrl: 'http://ya.ru')
Мы будем устанавливать baseUrl сразу в Dio. А не у конкретного API.
Так будет проще подменять разные сервера.

Так что здесь можно убрать.

2021-12-13 08:12 UTC, artem-zaitsev commented on lib/src/auth/services/api/auth_api.dart
> +abstract class RestClient {
Назови его AuthApi

2021-12-13 08:12 UTC, artem-zaitsev commented on lib/src/auth/services/api/auth_api.dart
> +  Future<List<Response>> getResponses();
здесь будут методы из тега Авторизация в АПИ.

2021-12-13 08:12 UTC, artem-zaitsev commented on lib/src/domain/token.dart
> +class Token {
все верно, только descripton - это лишнее. Это не часть модели, а служебное поле в yaml файле для описания документации.

2021-12-13 08:41 UTC, Salnikova-EO commented on lib/src/auth/services/api/auth_api.dart
> +@RestApi(baseUrl: 'http://ya.ru')
Я попыталась получить baseUrl через глобальные зависимости:
 var baseAppUrl = AppDependencies().dio.options.baseUrl;
Но когда ставлю в @RestAPi(baseUrl), выдаёт ошибку.

2021-12-15 07:55 UTC, artem-zaitsev requested changes

2021-12-15 07:55 UTC, artem-zaitsev commented on lib/src/auth/api/models/vc_login_response.dart
> +class VcLoginResponse {
Скорее VK - это его латинское название.

2021-12-15 07:55 UTC, artem-zaitsev commented on lib/src/auth/services/api/auth_api.dart
> +  String? content;
Тело ответа выглядит не так :
https://github.com/boostgrade/wtgt_api/blob/103a3a2705bb3f657919f2b724dcaf88305c4a19/_models/auth.yaml#L108
```
{
  "user: { // модель юзера },
  "token": { //модель токена }
}
```

2021-12-15 07:55 UTC, artem-zaitsev commented on lib/src/auth/services/api/auth_api.dart
> +  Future<List<AuthResponse>> getAppleResponses();
лучше в этих методах отойти от префикса get - просто loginBy..

2021-12-15 07:55 UTC, artem-zaitsev commented on lib/src/auth/services/api/auth_api.dart
> +  @POST('login_apple')
В аргументах у аннотации должен быть end-point, часть url этого метода: /login/apple в данном случае

этот и ниже комментарий касаются и всех методов ниже

2021-12-15 07:55 UTC, artem-zaitsev commented on lib/src/auth/services/api/auth_api.dart
> +  Future<List<AuthResponse>> getAppleResponses();
Так же не хватает Body()

Это POST запрос, у него есть тело, которое передается в параметрах. https://pub.dev/packages/retrofit#http-methods

По сути у тебя будет 
```
Future<AuthResponse> loginByApple(@Body() LoginByAppleRequest body);
```

1. Не совсем понял почему  у тебя сейчас возвращается List 
2. Тебе надо будет сделать модельки для тел запросов

2021-12-15 07:55 UTC, artem-zaitsev commented on lib/src/auth/api/models/meta_login_response.dart
> +  final String content;
почему у тебя всегда String content?

2021-12-17 10:08 UTC, artem-zaitsev requested changes

2021-12-17 10:08 UTC, artem-zaitsev commented on lib/src/auth/services/api/auth_api.dart
> +  AuthResponse({token, user});
{ required this.token, required this.user }

А то сейчас у тебя dynamic аргумениы и они не проставляются в поля.

2021-12-17 10:08 UTC, artem-zaitsev commented on lib/src/domain/token.dart
> +class Token {
там еще вроде refreshToken есть, проверь

2021-12-17 10:08 UTC, artem-zaitsev commented on lib/src/auth/api/models/requests/login_by_apple_request.dart
> +  final String content;
Лучше назвать это поле по аналогии с тем, как оно выглядит в АПИ. Иначе сервер не правильно распарсит данные.

2021-12-23 13:39 UTC, artem-zaitsev requested changes
Стало почти отлично!

1. Лишний объект для рефреша
2. Неверный респонс на токен
3. Ну и мелочи, чтобы сделать покрасивее

2021-12-23 13:39 UTC, artem-zaitsev commented on lib/src/domain/refresh_token.dart
> +}
У тебя будет единая модель токена:
```
class Token {
  final String token;
  final String refreshToken;
  //...
}
```
Нет смысла их прям так детально разделять. к тому же они в одном объекте и приходят.

2021-12-23 13:39 UTC, artem-zaitsev commented on lib/src/modules/auth/services/api/auth_api.dart
> +  Future<void> logout();
форматирование уехало: либо 
```
 flutter format .
```
  в консоли надо выполнить, либо Ctrl+Alt+F в IDE(хотя с точным сочетанием могу ошибится на винде)

2021-12-23 13:39 UTC, artem-zaitsev commented on lib/src/modules/auth/services/api/models/responses/token_response.dart
> +  final String token;
Тут два поля вроде
![image](https://user-images.githubusercontent.com/19290576/147248194-e83e4746-2e74-430a-87e6-63633b02ffb0.png)

2021-12-23 13:39 UTC, artem-zaitsev commented on lib/src/modules/auth/services/repository/auth_repository.dart
> +      return response; //
тут вообще не будет  return,   просто вызов метода АПИ

2021-12-23 13:39 UTC, artem-zaitsev commented on lib/src/modules/auth/services/repository/auth_repository.dart
> +  LoginModel getLoginModel(response){
лучше mapResponseToLoginModel().
И тип в аргументах укажи

2021-12-25 11:25 UTC, artem-zaitsev approved these changes
Сливаю

2021-12-25 12:18 UTC, merged