bloc авторизации
boostgrade/wtgt_alpha pull request #27
Opened 2021-12-16 06:50 UTC by Akrid782

[# Ссылка на задачу](https://github.com/boostgrade/wtgt_alpha/issues/12)
Задача #12 

# Что было сделано

Был реализован Bloc для моудля авторизаци, события, состояния данных и спроектированы события и состояния.

# Как проверить работу?

Пока никак, нужно реализовать методы реализации этих событий.

# Чек-лист

- [ ] Функциональность протестирована и работает корректно
- [ ] Если в задаче есть верстка - прикреплен скриншот или запись экрана

2021-12-17 10:03 UTC, artem-zaitsev requested changes
небольшая правка

2021-12-17 10:03 UTC, artem-zaitsev commented on lib/src/modules/auth/service/auth_bloc.dart
> +    on<RegistrationEvent>((event, emit) {});
сделай emit событий загрузки и успеха, а межуд ними поставь TODO: с описанием что надо обратиться к серверу

2021-12-21 05:41 UTC, Akrid782 commented on lib/src/modules/auth/service/auth_bloc.dart
> +    on<RegistrationEvent>((event, emit) {});
Поправил

2021-12-21 08:20 UTC, artem-zaitsev approved these changes

2021-12-21 08:20 UTC, merged