Тема приложения
boostgrade/wtgt_alpha pull request #28
Opened 2021-12-21 06:54 UTC by Akrid782

# [Ссылка на задачу](https://github.com/boostgrade/wtgt_alpha/issues/1)
Задача #1 

# Что было сделано

Добавлен класс для настройки темы приложения

# Как проверить работу?

Добавить тему из класс ProjectTheme в MaterialApp

# Чек-лист

- [ ] Функциональность протестирована и работает корректно
- [ ] Если в задаче есть верстка - прикреплен скриншот или запись экрана

2021-12-21 08:19 UTC, artem-zaitsev requested changes

2021-12-21 08:19 UTC, artem-zaitsev commented on lib/src/ui/res/theme/project_theme.dart
> +    return ThemeData(
Настрой InputDecorationTheme? inputDecorationTheme. Пригодится для кнопок

2021-12-21 08:19 UTC, artem-zaitsev commented on lib/src/ui/res/theme/project_theme.dart
> +    return ThemeData(
Точнее для текстовых полей

2021-12-26 15:39 UTC, Akrid782 commented on lib/src/ui/res/theme/project_theme.dart
> +    return ThemeData(
Добавил InputDecorationTheme

2021-12-27 07:30 UTC, artem-zaitsev approved these changes

2021-12-27 07:31 UTC, merged