init code store
boostgrade/wtgt_alpha pull request #29
Opened 2021-12-27 11:03 UTC by Akrid782

[# Ссылка на задачу](https://github.com/boostgrade/wtgt_alpha/issues/14)
Задача #14 

# Что было сделано

-

# Как проверить работу?

-

# Чек-лист

- [ ] Функциональность протестирована и работает корректно
- [ ] Если в задаче есть верстка - прикреплен скриншот или запись экрана

2022-01-14 10:17 UTC, artem-zaitsev requested changes

2022-01-14 10:17 UTC, artem-zaitsev commented on lib/src/di/app_dependency.dart
> +  final authController = AuthBloc(AuthService());
лучше authBloc

2022-01-14 10:17 UTC, artem-zaitsev commented on lib/src/modules/auth/service/auth_bloc.dart
> +  AuthBloc(AuthService authService) : super(LoadingState()) {
тут надо в конструктор передавать репозиторий, а не сервис - его сделал Катя

2022-01-14 10:17 UTC, artem-zaitsev commented on lib/src/modules/auth/service/auth_service.dart
> +class AuthService {}
это лишнее

2022-01-14 10:17 UTC, artem-zaitsev commented on lib/src/modules/auth/ui/code/code_store.dart
> +class CodeStore = _CodeStore with _$CodeStore;
Давай именовать CodeVm

2022-01-14 10:17 UTC, artem-zaitsev commented on lib/src/modules/auth/ui/code/code_store.dart
> +class CodeStore = _CodeStore with _$CodeStore;
ну и дальше по аналогии, вместо Store -> Vm (в файлах тоже)

2022-01-14 10:17 UTC, artem-zaitsev commented on lib/src/modules/auth/ui/code/code_store.dart
> +  // ignore: unused_field
игноры потом убери

2022-01-14 10:17 UTC, artem-zaitsev commented on lib/src/modules/auth/ui/code/code_store.dart
> +  void onCodeChanged(String value) {
тут можно будет сделать круче - завести TextEditingController внутри вьюмодели и в конструкторе вьюмодели подписать на его изменение эту функцию через addListener

2022-01-14 10:17 UTC, artem-zaitsev commented on lib/src/modules/auth/ui/code/code_view.dart
> +class _CodeViewState extends State<CodeView> with ViewModelDisposerMixin {
я там подлил типизацию миксина ViewModelDisposer - исправь, чтобы внутри этого класса все вызывать через vm, а не widget.store

2022-01-15 13:52 UTC, Akrid782 commented on lib/src/modules/auth/service/auth_bloc.dart
> +  AuthBloc(AuthService authService) : super(LoadingState()) {
поправил

2022-01-15 13:52 UTC, Akrid782 commented on lib/src/modules/auth/service/auth_service.dart
> +class AuthService {}
Убрал

2022-01-15 13:53 UTC, Akrid782 commented on lib/src/modules/auth/ui/code/code_store.dart
> +class CodeStore = _CodeStore with _$CodeStore;
Сделал

2022-01-15 13:53 UTC, Akrid782 commented on lib/src/modules/auth/ui/code/code_store.dart
> +  // ignore: unused_field
Убрал

2022-01-15 13:53 UTC, Akrid782 commented on lib/src/modules/auth/ui/code/code_store.dart
> +  void onCodeChanged(String value) {
Сделал через Controller

2022-01-15 13:53 UTC, Akrid782 commented on lib/src/modules/auth/ui/code/code_view.dart
> +class _CodeViewState extends State<CodeView> with ViewModelDisposerMixin {
Сделал

2022-01-17 08:01 UTC, artem-zaitsev commented on lib/src/modules/auth/ui/code/code_vm.dart
> +    isLoadingButton = false;
кажется сбрасывать надо только в случае SuccessState

2022-01-17 08:01 UTC, artem-zaitsev commented on lib/src/modules/auth/ui/code/code_vm.dart
> +  void _onStartTimer() {
я бы назвал _startTimer

2022-01-17 12:04 UTC, Akrid782 commented on lib/src/modules/auth/ui/code/code_vm.dart
> +    isLoadingButton = false;
А что делать если ошибка?

2022-01-18 05:27 UTC, Akrid782 commented on lib/src/modules/auth/ui/code/code_vm.dart
> +  void _onStartTimer() {
Поправил

2022-01-18 05:27 UTC, Akrid782 commented on lib/src/modules/auth/ui/code/code_vm.dart
> +    isLoadingButton = false;
Поправил

2022-01-18 09:18 UTC, artem-zaitsev requested changes
Небольшая правка

2022-01-18 09:18 UTC, artem-zaitsev commented on lib/src/modules/auth/ui/code/code_vm.dart
> +      isDisabledButton = text.isEmpty || text.length < 6 ? true : false;
isDisabledButton = text.isEmpty || text.length < 6;

Это уже логичекое выражение - возвращать явно true/false лишнее.

И стоит 6 вынести в константу

2022-01-22 07:19 UTC, Akrid782 commented on lib/src/modules/auth/ui/code/code_vm.dart
> +      isDisabledButton = text.isEmpty || text.length < 6 ? true : false;
Поправил

2022-01-23 10:24 UTC, artem-zaitsev approved these changes

2022-01-23 10:24 UTC, merged