Верстка экрана авторизации через СМС
boostgrade/wtgt_alpha pull request #31
Opened 2022-01-15 14:27 UTC by Akrid782

[# Ссылка на задачу](https://github.com/boostgrade/wtgt_alpha/issues/17)
Задача #17

# Что было сделано

- Добавил верстку экрана и воспользовался логикой прописанной в [задаче](https://github.com/boostgrade/wtgt_alpha/issues/14)
- Поправил тему приложения
- Добавил lang фразы
- Добавил логотип приложения
- Добавил цвет

Скриншоты:

![image](https://user-images.githubusercontent.com/20724267/149625141-82f6c449-6a43-4545-b331-c8438986caf8.png)

# Как проверить работу?

Добавить роут на lib\src\modules\auth\ui\code\code_screen.dart и добавить 

# Чек-лист

- [Х] Функциональность протестирована и работает корректно
- [Х] Если в задаче есть верстка - прикреплен скриншот или запись экрана

2022-01-17 09:32 UTC, artem-zaitsev requested changes
Написал правки, во многом все более менее хорошо.

2022-01-17 09:32 UTC, artem-zaitsev commented on lib/src/modules/auth/ui/code/code_screen.dart
> +  final CodeVm store;
давай лучше переименуем в vm

2022-01-17 09:32 UTC, artem-zaitsev commented on lib/src/modules/auth/ui/code/code_screen.dart
> +    });
и это тоже сделаем внутри vm.

Вроде такую реализацию и обсуждали в чате

2022-01-17 09:32 UTC, artem-zaitsev commented on lib/src/modules/auth/ui/code/code_screen.dart
> +      body: Container(
Если нужен только паддинг, логичнее использовать виджет Padding

2022-01-17 09:32 UTC, artem-zaitsev commented on lib/src/modules/auth/ui/code/code_screen.dart
> +                  child: Image.asset('assets/images/where_to_go_today'),
Для путей к ассетам давай сделаем класс, аналогичный Typography и цветам. Он будет содержать просто строковые константы с путями.

2022-01-17 09:32 UTC, artem-zaitsev commented on lib/src/modules/auth/ui/code/code_screen.dart
> +                    counterText: '',
Зачем каунтер?

2022-01-17 09:32 UTC, artem-zaitsev commented on lib/src/modules/auth/ui/code/code_screen.dart
> +                  //padding: const EdgeInsets.only(top: 32),
почему закомментировано и не указана причина?

2022-01-17 09:32 UTC, artem-zaitsev commented on lib/src/modules/auth/ui/code/code_screen.dart
> +                  alignment: Alignment.centerLeft,
если нужен только Alignment - есть виджет Align

2022-01-18 05:31 UTC, Akrid782 commented on lib/src/modules/auth/ui/code/code_screen.dart
> +/// Widgets that listen to the SettingsController are rebuilt.
Этого не должно было тут оказаться. 
Убрал

2022-01-18 05:32 UTC, Akrid782 commented on lib/src/modules/auth/ui/code/code_screen.dart
> +  final CodeVm store;
Поправил

2022-01-18 05:34 UTC, Akrid782 commented on lib/src/modules/auth/ui/code/code_screen.dart
> +      key: GlobalKey(),
Хорошо буду знать, тут действительно ключ не нужен.

Поправил

2022-01-18 05:36 UTC, Akrid782 commented on lib/src/modules/auth/ui/code/code_screen.dart
> +      body: Container(
Поправил

2022-01-18 05:37 UTC, Akrid782 commented on lib/src/modules/auth/ui/code/code_screen.dart
> +        padding: const EdgeInsets.all(30),
Если считать от поля, то 24, я считал от логотипа.

Поправил на 24

2022-01-18 05:41 UTC, Akrid782 commented on lib/src/modules/auth/ui/code/code_screen.dart
> +                  child: Image.asset('assets/images/where_to_go_today'),
Сделал

2022-01-18 05:42 UTC, Akrid782 commented on lib/src/modules/auth/ui/code/code_screen.dart
> +                    counterText: '',
Я его убрал тем самым. В фигме он не отображается, а тут таким способом я прячу его

2022-01-18 05:43 UTC, Akrid782 commented on lib/src/modules/auth/ui/code/code_screen.dart
> +                  //padding: const EdgeInsets.only(top: 32),
Я это закидывать не планировал, по этому убрал

2022-01-18 05:44 UTC, Akrid782 commented on lib/src/modules/auth/ui/code/code_screen.dart
> +                  alignment: Alignment.centerLeft,
Поправил

2022-01-18 05:44 UTC, Akrid782 commented on lib/src/modules/auth/ui/code/code_screen.dart
> +              // height: double.infinity,
Убрал, тут это не нужно

2022-01-18 05:58 UTC, Akrid782 commented on lib/src/modules/auth/ui/code/code_screen.dart
> +  final TextEditingController _controller = TextEditingController();
Перенес

2022-01-18 05:58 UTC, Akrid782 commented on lib/src/modules/auth/ui/code/code_screen.dart
> +    });
Да, я не туда вынес.

2022-01-18 05:59 UTC, Akrid782 commented on lib/src/modules/auth/ui/code/code_screen.dart
> +                  maxLength: 6,
Вынес в константу

2022-01-18 09:20 UTC, artem-zaitsev commented on lib/src/modules/auth/ui/code/code_screen.dart
> +                    counterText: '',
Если ты его не укажешь он будет null и его не будет.

2022-01-25 07:29 UTC, artem-zaitsev commented on lib/src/modules/auth/ui/code/code_route.dart
> +/// Маршрут для навигации к экрану настроек(сделан для примера)
описание не забывай менять на актуальное

2022-01-26 06:02 UTC, Akrid782 commented on lib/src/modules/auth/ui/code/code_route.dart
> +/// Маршрут для навигации к экрану настроек(сделан для примера)
Поправил

2022-01-29 09:25 UTC, artem-zaitsev approved these changes

2022-01-29 09:30 UTC, merged