интерцептор из образца
boostgrade/wtgt_alpha pull request #6
Opened 2021-11-28 14:18 UTC by Salnikova-EO

# Ссылка на задачу
Задача #Реализовать интерцептор для обработки ошибок сервера

# Что было сделано
Класс ProjectInterceptor из  примера https://blog.logrocket.com/networking-flutter-using-dio/
Прописала его в dio_module.dart

# Как проверить работу?

Вот тут у меня ничего и не получается

2021-11-28 15:35 UTC, artem-zaitsev commented on lib/src/services/network/dio/project_interceptor.dart
> +    return super.onRequest(options, handler);
Вот тут как раз момент, с измененным АПИ у dio: https://pub.dev/packages/dio#interceptors

Теперь вместо super.on... надо использовать handler и его методы:
- next() - когда мы передаем обработку далее(все что необходимо сделали, изменили, отадем следующему обработчику)
- error() - когда прекращаем обработку с ошибкой
- resolve() - когда прекращаем обработку с успехом.

В данном классе скорее нужен next()

2021-11-28 15:35 UTC, artem-zaitsev commented on lib/src/services/network/dio/project_interceptor.dart
> +    return super.onRequest(options, handler);
(но в super все равно он вызывается, так что не страшно. но лучше пользоваться handler для большей явности)

2021-12-02 09:30 UTC, artem-zaitsev requested changes
Напрвление верное, отсалось все это связать со StatusMapper и сделать новые классы для Exceptions

2021-12-02 09:30 UTC, artem-zaitsev commented on lib/src/modules/main/main_screen.dart
> +   // context.read<AppDependencies>().dio.get('http://ya.ru/'); // 200
вообще дебажные проверки и код убираем из пуллреквеста при готовности

2021-12-02 09:30 UTC, artem-zaitsev commented
И исправить предупреждения

2021-12-03 08:04 UTC, artem-zaitsev requested changes
Направление верное, осталось сделать небольшой еще шажок

2021-12-03 08:04 UTC, artem-zaitsev commented on lib/src/services/exceptions/server/server_exceptions.dart
> +class BadRequestException implements Exception {}
Давайте писать описание к классам через ///

Так будет точно понятно, что это за ошибка и когда выбрасывается.
Для примера:
Исключение, выбрасываемое при появлении 400 HTTP-кода


К тому же 400 код еще содержит тело ответа:
{"message: string, "code": string} - его надо распарсить и передать сообщение в исключение, через конструктор.

Для парсинга лучше использовать https://pub.dev/packages/json_serializable

2021-12-03 08:04 UTC, artem-zaitsev commented on lib/src/services/network/dio/project_interceptor.dart
> +class ProjectInterceptor extends Interceptor {
Давай его переименуем(нейминг сейчас не очень понятный - непонятно что именно делает этот интерцептор) в ErrorInterceptor.

И убери onReuqest и onResponse - они аналогичны у базового класса.

2021-12-03 08:04 UTC, artem-zaitsev commented on lib/src/services/network/dio/project_interceptor.dart
> +class ProjectInterceptor extends Interceptor {
И описание к классу

2021-12-03 08:04 UTC, artem-zaitsev commented on lib/src/services/network/dio/project_interceptor.dart
> +      }
тут надо просто вызвать StatusMapper -  ведь он делает ровно то же самое. 
По сути это дублирование логики и противоречит принципу DRY(Don't Repeat Yourself)

2021-12-03 08:08 UTC, Salnikova-EO commented on lib/src/services/network/dio/project_interceptor.dart
> +      }
StatusMapper == ServerErrorMapper?

2021-12-05 07:30 UTC, Salnikova-EO commented on lib/src/services/exceptions/server/server_exceptions.dart
> +class BadRequestException implements Exception {}
С парсингом не поняла. Что именно мы парсим? У меня есть err.response?.statusCode - код ошибки, err.response?.statusMessage - сообщение и err.response?.data - туда пихается целиком страница с ошибкой.

2021-12-06 07:16 UTC, artem-zaitsev requested changes
все хорошо, только немного наведи порядок в коде

2021-12-06 07:16 UTC, artem-zaitsev commented on lib/src/services/exceptions/server/server_error_mapper.dart
> +  static Exception fromStatusCode(int? statusCode, String? message) {
почему ты сделала параметры nullable?

2021-12-06 07:16 UTC, artem-zaitsev commented on lib/src/services/exceptions/server/server_exceptions.dart
> +
пустые строки используем для отделения логически связанного кода.
А слишком много пустых строк подряд - ухудшают чиатемость.

2021-12-06 07:16 UTC, artem-zaitsev commented on lib/src/services/network/dio/project_interceptor.dart
> +      return handler.next(err);
форматирование уехало

2021-12-06 07:29 UTC, artem-zaitsev requested changes
Не все еще сделала, я не сразу заметил.

2021-12-06 07:29 UTC, artem-zaitsev commented on lib/src/services/network/dio/project_interceptor.dart
> +    ServerErrorMapper.fromStatusCode(code, message);
Несколько моментов:
- ты ничего не делаешь с результатом этой функции(твоя ошибка уйдет в никуда, никем не будет использована)
- ты не парсишь тело ответа в случае 400 кода

2021-12-06 07:29 UTC, artem-zaitsev commented on lib/src/services/network/dio/project_interceptor.dart
> +      return handler.next(err);
сюда надо передат DioError с твоей новой ошибкой

2021-12-08 11:04 UTC, artem-zaitsev requested changes
Небольшой косметический комментарий

2021-12-08 11:04 UTC, artem-zaitsev commented on lib/src/services/exceptions/server/server_error_mapper.dart
> +      final  dataerr = ServerErrorResponse.fromJson(err.response?.data);
Давай только именовать так, чтобы легче читать: например errorData

2021-12-08 11:04 UTC, artem-zaitsev commented on lib/src/services/network/dio/project_interceptor.dart
> +
пустую строку убери только

2021-12-09 08:36 UTC, artem-zaitsev approved these changes

2021-12-09 08:36 UTC, merged