Base component button
boostgrade/wtgt_alpha pull request #9
Opened 2021-12-02 07:22 UTC by Akrid782

# [Ссылка на задачу](https://github.com/boostgrade/wtgt_alpha/issues/3)
Задача #3 

# Что было сделано

1. Добавлен localization фразы для кнопки en и ru - для смени языка в приложения
2. Создал ButtonWidget от наследованного от StatelessWidget с кнопкой ElevatedButton - кнопку выбрал такую потому что она с заливкой
3. Задан стиль кнопки в соответствии верстки в figme 
4. Было добавлено 3 состояния которые управляются через конструктор
5. Добавил цветовую схему в файл wtgt_alpha\lib\src\ui\res\colors\colors.dart 

# Как проверить работу?

1. Выбрать место где будет размещаться кнопка
2. Сделать импорт пакета 'package:where_to_go_today/src/ui/uikit/button_widget.dart'
3. Вставить код в нужное место

```dart
ButtonWidget(
  title: 'Заголовок кнопки',
  callBackPressed: () {
   print('Hi');
  } //'передать callback функцию void',
 process: false // сюда передать true если нужно показать прелоадер, по умолчанию false, не обязательный параметр
 disable: false // сюда передать true если нужно заблокировать кнопку, по умолчанию false, не обязательный параметр
)
```

![image](https://user-images.githubusercontent.com/20724267/144376152-0f9192cb-530b-48bf-8acf-97c2f3c7b266.png)
![image](https://user-images.githubusercontent.com/20724267/144376222-f31bd730-483c-4237-b137-cb6bda3f16cb.png)
![image](https://user-images.githubusercontent.com/20724267/144376290-3107b6f3-b029-48b5-871b-33c9d3b6428f.png)

# Чек-лист

- [X] Функциональность протестирована и работает корректно
- [X ] Если в задаче есть верстка - прикреплен скриншот или запись экрана

2021-12-02 09:30 UTC, artem-zaitsev commented
Ветки именуем: feature/над-чем-работаем

2021-12-02 09:34 UTC, artem-zaitsev requested changes
небольшие правки

2021-12-02 09:34 UTC, artem-zaitsev commented on lib/src/ui/uikit/button_widget.dart
> +    final Color textColor = (disable
скобки тут в общем-то лишние

2021-12-02 09:34 UTC, artem-zaitsev commented on lib/src/ui/uikit/button_widget.dart
> +  final void Function()? callBackPressed;
чаще используют onSomething названия для колбеков

2021-12-02 09:34 UTC, artem-zaitsev commented on lib/src/ui/uikit/button_widget.dart
> +          : const CircularProgressIndicator(
внутри кнопки от индикатора есть отступ, у тебя его нет)

2021-12-05 13:08 UTC, Akrid782 commented on lib/src/ui/uikit/button_widget.dart
> +          : const CircularProgressIndicator(
Поправил

2021-12-05 13:08 UTC, Akrid782 commented on lib/src/ui/uikit/button_widget.dart
> +  final void Function()? callBackPressed;
поправил

2021-12-05 13:08 UTC, Akrid782 commented on lib/src/ui/uikit/button_widget.dart
> +    final Color textColor = (disable
поправил

2021-12-06 07:13 UTC, artem-zaitsev commented
это закрою

2021-12-06 07:13 UTC, closed without merging